### ISSUE TITLE
OS Name Change

### ISSUE THREAD

**Issue by Qib10** [cl91/NeptuneOS#1]
Hi,

The name NeptuneOS is already used by one of the linux distributions 
https://neptuneos.com/en/start-page.html

How about OdysseyOS?
Inspired from "Windows Odyssey"

Sorry for bad English because I used translator :)

**Comment by cl91** [comment]
I like the name Neptune lol. The main point is that we can use the acronym "NTOS" to stand for "Neptune OS". This is all over the source code so I don't want to change it. Name conflict is perfectly fine as long as they live in different namespaces (one is a Linux distribution, another one is a seL4 "distribution").

**Comment by Qib10** [comment]
Lmao

**Comment by sskras** [comment]
> different namespaces (one is a Linux distribution, another one is a seL4 "distribution")

And if the namespaces / domains of use ever crosses over (eg. in some hypervisor maintaining the exact list of guess OS names), both monikers could get their own suffixes, like it happened with the `iotop` and `iotop-c` tools. Eg:

* Neptune (Neptune-Lin, Neptune-Deb)
* NeptuneOS (NeptuneOS-seL4, NeptuneOS-NT)
