### ISSUE TITLE
How can i emukate this in QEMU?

### ISSUE THREAD

**Issue by leapofazzam123** [cl91/NeptuneOS#13]
I got `fsgsbase instructions not supported by the processor` in the serial console

**Comment by cl91** [comment]
Set the emulated processor to at least ivy bridge with the `-cpu` option will solve this problem. The default amd64 emulation target of qemu doesn't enable the fsgsbase instruction which is needed for TLS (thread local storage). Have a look at the `run.sh` script in the repo which has the right qemu options.

**Comment by cl91** [comment]
Let me know if you get it working, I'll close the issue once you solve this problem (or you can close it yourself 🤣🤣).
